/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adati;

import Filter.*;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;
import backend.Histogram;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;



/**
 *
 * @author Simon
 */
public class windowMain extends javax.swing.JFrame {

    /**
     * Creates new form windowMAin
     */
    
    protected BufferedImage imageFirst;
    protected BufferedImage imageSource;
    protected BufferedImage imageDestination;
    String path;
    Graphics roiRect;
    ROI tmpROI = new ROI();
        
    public BufferedImage getBufferedSource(){return imageSource;}
    public BufferedImage getBufferedDestination(){return imageDestination;}
    
    public windowMain() {
        initComponents();
        GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int width = gd.getDisplayMode().getWidth();
        int height = gd.getDisplayMode().getHeight();
        this.setLocation(450, (height/2)-(this.getHeight()/2));
        this.setResizable(false);
        this.setTitle("Analyse design d'application et traitement d'image");
        
        Component[] componentsPanel1 = jPanel1.getComponents();
        for(int i = 0; i < componentsPanel1.length; i++) {
            componentsPanel1[i].setEnabled(false);
        }
        
        Component[] componentsPanel2 = jPanel2.getComponents();
        for(int i = 0; i < componentsPanel2.length; i++) {
            componentsPanel2[i].setEnabled(false);
        }
        
        Component[] componentsPanel3 = jPanel3.getComponents();
        for(int i = 0; i < componentsPanel3.length; i++) {
            componentsPanel3[i].setEnabled(false);
        }
        
        Component[] componentsPanel4 = jPanel4.getComponents();
        for(int i = 0; i < componentsPanel4.length; i++) {
            componentsPanel4[i].setEnabled(false);
        }
        
        Component[] componentsPanel5 = jPanel5.getComponents();
        for(int i = 0; i < componentsPanel5.length; i++) {
            componentsPanel5[i].setEnabled(false);
        }

        Component[] componentsPanel6 = jPanel6.getComponents();
        for(int i = 0; i < componentsPanel6.length; i++) {
            componentsPanel6[i].setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        imageSrc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        imageDest = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TransfertSrcDest = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        TransfertDestSrc = new javax.swing.JButton();
        ComboBoxZoom = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Button_Palette = new javax.swing.JButton();
        Button_Histogram = new javax.swing.JButton();
        Button_Expansion = new javax.swing.JButton();
        TextField_X = new javax.swing.JTextField();
        TextField_Y = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SpinnerWidth = new javax.swing.JSpinner();
        SpinnerHeight = new javax.swing.JSpinner();
        ButtonSetSize = new javax.swing.JButton();
        ButtonSetSizeBox = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button_ROI = new javax.swing.JButton();
        Button_GreyScale = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Button_Seuillage = new javax.swing.JButton();
        TextField_SeuillageSimple = new javax.swing.JTextField();
        Button_SeuillageMulti = new javax.swing.JButton();
        TextField_SeuillageMulti1 = new javax.swing.JTextField();
        TextField_SeuillageMulti2 = new javax.swing.JTextField();
        TextField_SeuillageMulti3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Button_Median = new javax.swing.JButton();
        Button_Moyen = new javax.swing.JButton();
        Button_Gaussien = new javax.swing.JButton();
        Button_Laplacien = new javax.swing.JButton();
        Button_Kirsch = new javax.swing.JButton();
        Button_Sobel = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Button_Prewitt = new javax.swing.JButton();
        Button_Roberts = new javax.swing.JButton();
        Button_Erosion = new javax.swing.JButton();
        Button_Dilatation = new javax.swing.JButton();
        Button_Ouverture = new javax.swing.JButton();
        Button_Fermeture = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        imageSrc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        imageSrc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        imageSrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imageSrcMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                imageSrcMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(imageSrc);

        imageDest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageDest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jScrollPane2.setViewportView(imageDest);

        TransfertSrcDest.setText("Source vers Destination ");
        TransfertSrcDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransfertSrcDestActionPerformed(evt);
            }
        });

        Reset.setText("Remettre à zéro");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        TransfertDestSrc.setText("Destination vers Source");
        TransfertDestSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransfertDestSrcActionPerformed(evt);
            }
        });

        ComboBoxZoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.5", "1", "2", "5" }));
        ComboBoxZoom.setSelectedIndex(1);
        ComboBoxZoom.setToolTipText("");
        ComboBoxZoom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxZoomItemStateChanged(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Zoom :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxZoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TransfertDestSrc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TransfertSrcDest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(Reset, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Reset)
                .addGap(18, 18, 18)
                .addComponent(TransfertSrcDest)
                .addGap(18, 18, 18)
                .addComponent(TransfertDestSrc)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_Palette.setText("Palette");
        Button_Palette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PaletteActionPerformed(evt);
            }
        });

        Button_Histogram.setText("Show Histogram");
        Button_Histogram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HistogramActionPerformed(evt);
            }
        });

        Button_Expansion.setText("Expansion / Extraction");
        Button_Expansion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExpansionActionPerformed(evt);
            }
        });

        TextField_X.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_X.setText("0");
        TextField_X.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        TextField_Y.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_Y.setText("0");
        TextField_Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_YActionPerformed(evt);
            }
        });

        jLabel5.setText("X :");

        jLabel6.setText("Y :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Palette, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(Button_Histogram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Expansion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_Y, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TextField_X))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Palette)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Histogram)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Expansion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_Y, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Taille :");

        ButtonSetSize.setText("Set size");
        ButtonSetSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSetSizeActionPerformed(evt);
            }
        });

        ButtonSetSizeBox.setText("Set Size box");
        ButtonSetSizeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSetSizeBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Width");

        jLabel3.setText("Height");

        Button_ROI.setText("ROI");
        Button_ROI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ROIActionPerformed(evt);
            }
        });

        Button_GreyScale.setText("GreyScale");
        Button_GreyScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GreyScaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonSetSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SpinnerHeight, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SpinnerWidth, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addComponent(ButtonSetSizeBox, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(Button_ROI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_GreyScale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSetSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonSetSizeBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_ROI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_GreyScale)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Button_Seuillage.setText("Seuillage simple");
        Button_Seuillage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeuillageActionPerformed(evt);
            }
        });

        Button_SeuillageMulti.setText("Seuillage multiple");
        Button_SeuillageMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeuillageMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Seuillage, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TextField_SeuillageSimple)
                    .addComponent(Button_SeuillageMulti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(TextField_SeuillageMulti1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_SeuillageMulti2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextField_SeuillageMulti3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Seuillage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_SeuillageSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_SeuillageMulti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_SeuillageMulti1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_SeuillageMulti2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_SeuillageMulti3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        Button_Median.setText("Filtre médian");
        Button_Median.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MedianActionPerformed(evt);
            }
        });

        Button_Moyen.setText("Filtre moyen");
        Button_Moyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MoyenActionPerformed(evt);
            }
        });

        Button_Gaussien.setText("Filtre gaussien");
        Button_Gaussien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GaussienActionPerformed(evt);
            }
        });

        Button_Laplacien.setText("Filtre laplacien");
        Button_Laplacien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LaplacienActionPerformed(evt);
            }
        });

        Button_Kirsch.setText("Filtre de Kirsch");
        Button_Kirsch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_KirschActionPerformed(evt);
            }
        });

        Button_Sobel.setText("Filtre de Sobel");
        Button_Sobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SobelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Median, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Button_Moyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Gaussien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Laplacien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Kirsch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Sobel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Median)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Moyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Gaussien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Laplacien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Kirsch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Sobel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Button_Prewitt.setText("Filtre de Prewitt");
        Button_Prewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PrewittActionPerformed(evt);
            }
        });

        Button_Roberts.setText("Filtre de Roberts");
        Button_Roberts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RobertsActionPerformed(evt);
            }
        });

        Button_Erosion.setText("Erosion");
        Button_Erosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ErosionActionPerformed(evt);
            }
        });

        Button_Dilatation.setText("Dilatation");
        Button_Dilatation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DilatationActionPerformed(evt);
            }
        });

        Button_Ouverture.setText("Ouverture");
        Button_Ouverture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_OuvertureActionPerformed(evt);
            }
        });

        Button_Fermeture.setText("Fermeture");
        Button_Fermeture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FermetureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Prewitt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Roberts, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(Button_Erosion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Dilatation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Ouverture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Fermeture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Prewitt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Roberts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Erosion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Dilatation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Ouverture)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Fermeture)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Ouvrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Save");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem2.setText("Reset");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Quitter");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
	jfc.setDialogTitle("Select an image");
	jfc.setAcceptAllFileFilterUsed(false);
        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
	FileNameExtensionFilter filter = new FileNameExtensionFilter("JPEG, BMP and GIF images", "jpg", "png", "bmp", "gif");
	jfc.addChoosableFileFilter(filter);

	int returnValue = jfc.showOpenDialog(null);
	if (returnValue == JFileChooser.APPROVE_OPTION) {
            System.out.println(jfc.getSelectedFile().getPath());
            path = jfc.getSelectedFile().getPath();
            
            try {
                imageFirst = convertToBuffered(ImageIO.read(new File(path)));
            } catch (IOException ex) {
                Logger.getLogger(windowMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            setBufferedSource(imageFirst);
            
            Component[] componentsPanel1 = jPanel1.getComponents();
            for(int i = 0; i < componentsPanel1.length; i++) {
                componentsPanel1[i].setEnabled(true);
            }

            Component[] componentsPanel2 = jPanel2.getComponents();
            for(int i = 0; i < componentsPanel2.length; i++) {
                componentsPanel2[i].setEnabled(true);
            }
            
            Component[] componentsPanel3 = jPanel3.getComponents();
            for(int i = 0; i < componentsPanel3.length; i++) {
                componentsPanel3[i].setEnabled(true);
            }
            
            Component[] componentsPanel4 = jPanel4.getComponents();
            for(int i = 0; i < componentsPanel4.length; i++) {
                componentsPanel4[i].setEnabled(true);
            }
            
            Component[] componentsPanel5 = jPanel5.getComponents();
            for(int i = 0; i < componentsPanel5.length; i++) {
                componentsPanel5[i].setEnabled(true);
            }

            Component[] componentsPanel6 = jPanel6.getComponents();
            for(int i = 0; i < componentsPanel6.length; i++) {
                componentsPanel6[i].setEnabled(true);
            }
	}
        else
        {
            JOptionPane.showMessageDialog(new JFrame(), "Une erreur est survenue lors de l'ouverture de l'image", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void TransfertSrcDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransfertSrcDestActionPerformed
        if(imageSrc.getIcon() != null)
        {
            setBufferedDestination(imageSource);
        }
        else {
            JOptionPane.showMessageDialog(new JFrame(), "Pas d'image à transférer", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_TransfertSrcDestActionPerformed

    private void TransfertDestSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransfertDestSrcActionPerformed
        
        if(imageDest.getIcon() != null)
        {
            setBufferedSource(imageDestination);
        }
        else {
            JOptionPane.showMessageDialog(new JFrame(), "Pas d'image à transférer", "Erreur", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_TransfertDestSrcActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        imageSrc.setIcon(null);
        imageDest.setIcon(null);
        Component[] componentsPanel1 = jPanel1.getComponents();
        for(int i = 0; i < componentsPanel1.length; i++) {
            componentsPanel1[i].setEnabled(false);
        }
        
        Component[] componentsPanel2 = jPanel2.getComponents();
        for(int i = 0; i < componentsPanel2.length; i++) {
            componentsPanel2[i].setEnabled(false);
        }
        
        Component[] componentsPanel3 = jPanel3.getComponents();
        for(int i = 0; i < componentsPanel3.length; i++) {
            componentsPanel3[i].setEnabled(false);
        }
        
        Component[] componentsPanel4 = jPanel4.getComponents();
        for(int i = 0; i < componentsPanel4.length; i++) {
            componentsPanel4[i].setEnabled(false);
        }
        
        Component[] componentsPanel5 = jPanel5.getComponents();
        for(int i = 0; i < componentsPanel5.length; i++) {
            componentsPanel5[i].setEnabled(false);
        }
        
        Component[] componentsPanel6 = jPanel6.getComponents();
        for(int i = 0; i < componentsPanel6.length; i++) {
            componentsPanel6[i].setEnabled(false);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        imageDest.setIcon(null);
        setBufferedSource(imageFirst);
    }//GEN-LAST:event_ResetActionPerformed

    private void ButtonSetSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSetSizeActionPerformed
        if(SpinnerHeight.getValue().equals(null) || SpinnerWidth.getValue().equals(null))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Les valeurs entrées ne sont pas bonne.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else {            
            Image tmpImage = imageSource.getSubimage(0, 0, imageSource.getWidth(), imageSource.getHeight());
            tmpImage = tmpImage.getScaledInstance((int) SpinnerWidth.getValue(), (int) SpinnerHeight.getValue(), Image.SCALE_DEFAULT);

            BufferedImage tmp = convertToBuffered(tmpImage);
            setBufferedSource(tmp);
        }
    }//GEN-LAST:event_ButtonSetSizeActionPerformed

    private void ButtonSetSizeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSetSizeBoxActionPerformed
        Image tmpImage = imageSource.getSubimage(0, 0, imageSource.getWidth(), imageSource.getHeight());
        tmpImage = tmpImage.getScaledInstance((int) imageSrc.getVisibleRect().getWidth(), (int) imageSrc.getVisibleRect().getHeight(), Image.SCALE_DEFAULT);
        
        BufferedImage tmp = convertToBuffered(tmpImage);
        setBufferedSource(tmp);
    }//GEN-LAST:event_ButtonSetSizeBoxActionPerformed

    private void Button_ROIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ROIActionPerformed
        if(tmpROI.getXRoi() == 0 || tmpROI.getYRoi() == 0 || tmpROI.getWidthRoi() == 0 || tmpROI.getHeightRoi() == 0)
        {
            JOptionPane.showMessageDialog(new JFrame(), "Selectionner une partie de l'image.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else {
            BufferedImage tmp = imageSource.getSubimage(tmpROI.getXRoi(), tmpROI.getYRoi(), tmpROI.getWidthRoi(),tmpROI.getHeightRoi());
            setBufferedDestination(tmp);
        }

    }//GEN-LAST:event_Button_ROIActionPerformed

    private void ComboBoxZoomItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxZoomItemStateChanged

            int zoom = ComboBoxZoom.getSelectedIndex();
            
            Image tmpImage = imageSource.getSubimage(0, 0, imageSource.getWidth(), imageSource.getHeight());
            
            switch(zoom)
            {
                case 0: tmpImage = tmpImage.getScaledInstance(imageSource.getWidth()/2, imageSource.getHeight()/2, Image.SCALE_DEFAULT);
                    break;
                
                case 1: tmpImage = tmpImage.getScaledInstance(imageSource.getWidth(), imageSource.getHeight(), Image.SCALE_DEFAULT);
                    break;
                
                case 2: tmpImage = tmpImage.getScaledInstance(imageSource.getWidth()*2, imageSource.getHeight()*2, Image.SCALE_DEFAULT);
                    break;
                
                case 3: tmpImage = tmpImage.getScaledInstance(imageSource.getWidth()*5, imageSource.getHeight()*5, Image.SCALE_DEFAULT);
                    break;
            }
            
            BufferedImage tmp = convertToBuffered(tmpImage);
            setBufferedSource(tmp);
    }//GEN-LAST:event_ComboBoxZoomItemStateChanged

    private void imageSrcMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageSrcMouseReleased
        // TODO add your handling code here:
        System.out.println(evt.getX() + " " + evt.getY() );
        
        tmpROI.setX2Roi(evt.getX());
        tmpROI.setY2Roi(evt.getY());
    }//GEN-LAST:event_imageSrcMouseReleased

    private void imageSrcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageSrcMousePressed
        // TODO add your handling code here:
        System.out.println(evt.getX() + " " + evt.getY() );
        tmpROI.setXRoi(evt.getX());
        tmpROI.setYRoi(evt.getY());
    }//GEN-LAST:event_imageSrcMousePressed

    private void Button_PaletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PaletteActionPerformed
        // TODO add your handling code here:
        paletteDialog PD = new paletteDialog(this, true);
        PD.setVisible(true);
    }//GEN-LAST:event_Button_PaletteActionPerformed

    private void Button_HistogramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HistogramActionPerformed
        Histogram histogram = new Histogram(this, false);
        histogram.setVisible(true);
    }//GEN-LAST:event_Button_HistogramActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        File file = new File("C:\\Users\\Simon\\Desktop\\out.jpg");
        try {
            ImageIO.write(getBufferedSource(), "jpg", file);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), e.toString(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void Button_ExpansionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExpansionActionPerformed
        // TODO add your handling code here:
        if(TextField_X.getText().equals("0") && TextField_Y.getText().equals("0"))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Entrer un X ou un Y correct.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            Expansion img = new Expansion(getBufferedSource(), Float.parseFloat(TextField_X.getText()), Float.parseFloat(TextField_Y.getText()));
            setBufferedDestination(img.getExpansion());
        }
    }//GEN-LAST:event_Button_ExpansionActionPerformed

    private void Button_GreyScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GreyScaleActionPerformed
        // TODO add your handling code here:
        GreyScale imgToGrey = new GreyScale(getBufferedSource());
        setBufferedDestination(imgToGrey.getImgToGray());
    }//GEN-LAST:event_Button_GreyScaleActionPerformed

    private void TextField_YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_YActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_YActionPerformed

    private void Button_SeuillageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeuillageActionPerformed
        // TODO add your handling code here:
        if(TextField_SeuillageSimple.getText().equals("0") || TextField_SeuillageSimple.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Entrer un seuillage correct.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            SimpleThresholding st = new SimpleThresholding(getBufferedSource(), Integer.parseInt(TextField_SeuillageSimple.getText()));
            setBufferedDestination(st.getSimpleThresholding());
        }
    }//GEN-LAST:event_Button_SeuillageActionPerformed

    private void Button_SeuillageMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeuillageMultiActionPerformed
        // TODO add your handling code here:
        if(TextField_SeuillageMulti1.getText().equals("0") || TextField_SeuillageMulti1.getText().equals("") || TextField_SeuillageMulti2.getText().equals("0") || TextField_SeuillageMulti2.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new JFrame(), "Entrer un seuillage correct.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            MultiThresholding mt = new MultiThresholding(getBufferedSource(), Integer.parseInt(TextField_SeuillageMulti1.getText()),Integer.parseInt(TextField_SeuillageMulti2.getText()),Integer.parseInt(TextField_SeuillageMulti3.getText()));
            setBufferedDestination(mt.getMultiThresholding());
        }
    }//GEN-LAST:event_Button_SeuillageMultiActionPerformed

    private void Button_SobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SobelActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        SobelFilter sf = new SobelFilter(gs.getImgToGray());
        setBufferedDestination(sf.getSobelFilter());
    }//GEN-LAST:event_Button_SobelActionPerformed

    private void Button_MedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MedianActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        MedianFilter mf = new MedianFilter(gs.getImgToGray());
        setBufferedDestination(mf.getMedianFilter());
    }//GEN-LAST:event_Button_MedianActionPerformed

    private void Button_MoyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MoyenActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        MeanFilter mf = new MeanFilter(gs.getImgToGray());
        setBufferedDestination(mf.getMeanFilter());
    }//GEN-LAST:event_Button_MoyenActionPerformed

    private void Button_GaussienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GaussienActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        GaussienFilter gf = new GaussienFilter(gs.getImgToGray());
        setBufferedDestination(gf.getGaussienFilter());
    }//GEN-LAST:event_Button_GaussienActionPerformed

    private void Button_LaplacienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LaplacienActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        LaplacienFilter lf = new LaplacienFilter(gs.getImgToGray());
        setBufferedDestination(lf.getLaplacienFilter());
    }//GEN-LAST:event_Button_LaplacienActionPerformed

    private void Button_KirschActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_KirschActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        KirschFilter kf = new KirschFilter(gs.getImgToGray());
        setBufferedDestination(kf.getKirschFilter());
    }//GEN-LAST:event_Button_KirschActionPerformed

    private void Button_PrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PrewittActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        PrewittFilter pf = new PrewittFilter(gs.getImgToGray());
        setBufferedDestination(pf.getPrewittFilter());
    }//GEN-LAST:event_Button_PrewittActionPerformed

    private void Button_RobertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RobertsActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        RobertsFilter rf = new RobertsFilter(gs.getImgToGray());
        setBufferedDestination(rf.getRobertsFilter());
    }//GEN-LAST:event_Button_RobertsActionPerformed

    private void Button_ErosionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ErosionActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        Erosion e = new Erosion(gs.getImgToGray());
        setBufferedDestination(e.getErosion());
    }//GEN-LAST:event_Button_ErosionActionPerformed

    private void Button_DilatationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DilatationActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        Dilatation d = new Dilatation(gs.getImgToGray());
        setBufferedDestination(d.getDilatation());
    }//GEN-LAST:event_Button_DilatationActionPerformed

    private void Button_OuvertureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_OuvertureActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        Erosion e = new Erosion(gs.getImgToGray());
        Dilatation d = new Dilatation(e.getErosion());
        setBufferedDestination(d.getDilatation());
    }//GEN-LAST:event_Button_OuvertureActionPerformed

    private void Button_FermetureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FermetureActionPerformed
        GreyScale gs = new GreyScale(getBufferedSource());
        Dilatation d = new Dilatation(gs.getImgToGray());
        Erosion e = new Erosion(d.getDilatation());
        setBufferedDestination(e.getErosion());
    }//GEN-LAST:event_Button_FermetureActionPerformed

    
    public BufferedImage convertToBuffered(Image img)
    {
        if (img instanceof BufferedImage)
        {
            return (BufferedImage) img;
        }

        BufferedImage bImage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        Graphics2D bGr = bImage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();

        return bImage;
    }
    
    public void setBufferedSource(BufferedImage src)
    {
        imageSource = new BufferedImage(src.getWidth(), src.getHeight(), src.getType()); 
        Graphics g = imageSource.getGraphics();
        g.drawImage(src, 0, 0, this);
        g.dispose();
        
        ImageIcon imageIcon = new ImageIcon(src); 
        imageSrc.setIcon(imageIcon);
    }
    
    public void setBufferedDestination(BufferedImage dest)
    { 
        imageDestination = new BufferedImage(dest.getWidth(), dest.getHeight(), dest.getType()); 
        Graphics g = imageDestination.getGraphics();
        g.drawImage(dest, 0, 0, this);
        g.dispose();

        ImageIcon imageIcon = new ImageIcon(dest); 
        imageDest.setIcon(imageIcon);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(windowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(windowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(windowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(windowMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new windowMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonSetSize;
    private javax.swing.JButton ButtonSetSizeBox;
    private javax.swing.JButton Button_Dilatation;
    private javax.swing.JButton Button_Erosion;
    private javax.swing.JButton Button_Expansion;
    private javax.swing.JButton Button_Fermeture;
    private javax.swing.JButton Button_Gaussien;
    private javax.swing.JButton Button_GreyScale;
    private javax.swing.JButton Button_Histogram;
    private javax.swing.JButton Button_Kirsch;
    private javax.swing.JButton Button_Laplacien;
    private javax.swing.JButton Button_Median;
    private javax.swing.JButton Button_Moyen;
    private javax.swing.JButton Button_Ouverture;
    private javax.swing.JButton Button_Palette;
    private javax.swing.JButton Button_Prewitt;
    private javax.swing.JButton Button_ROI;
    private javax.swing.JButton Button_Roberts;
    private javax.swing.JButton Button_Seuillage;
    private javax.swing.JButton Button_SeuillageMulti;
    private javax.swing.JButton Button_Sobel;
    private javax.swing.JComboBox<String> ComboBoxZoom;
    private javax.swing.JButton Reset;
    private javax.swing.JSpinner SpinnerHeight;
    private javax.swing.JSpinner SpinnerWidth;
    private javax.swing.JTextField TextField_SeuillageMulti1;
    private javax.swing.JTextField TextField_SeuillageMulti2;
    private javax.swing.JTextField TextField_SeuillageMulti3;
    private javax.swing.JTextField TextField_SeuillageSimple;
    private javax.swing.JTextField TextField_X;
    private javax.swing.JTextField TextField_Y;
    private javax.swing.JButton TransfertDestSrc;
    private javax.swing.JButton TransfertSrcDest;
    private javax.swing.JLabel imageDest;
    public javax.swing.JLabel imageSrc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
